Repository Ato-viExpert/Ato-visionOS, pull requests merged in 2025-07, with the labels that each got.

#3 [Setting] #1 - xcode setting했습니다.
  .gitignore
  Ato-visionOS/Ato-visionOS.xcodeproj/project.pbxproj
  Ato-visionOS/Ato-visionOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Ato-visionOS/Ato-visionOS/AppModel.swift
  Ato-visionOS/Ato-visionOS/Assets.xcassets/AccentColor.colorset/Contents.json
  Ato-visionOS/Ato-visionOS/Assets.xcassets/AppIcon.solidimagestack/Back.solidimagestacklayer/Content.imageset/Contents.json
  Ato-visionOS/Ato-visionOS/Assets.xcassets/AppIcon.solidimagestack/Back.solidimagestacklayer/Contents.json
  Ato-visionOS/Ato-visionOS/Assets.xcassets/AppIcon.solidimagestack/Contents.json
  Ato-visionOS/Ato-visionOS/Assets.xcassets/AppIcon.solidimagestack/Front.solidimagestacklayer/Content.imageset/Contents.json
  Ato-visionOS/Ato-visionOS/Assets.xcassets/AppIcon.solidimagestack/Front.solidimagestacklayer/Contents.json
  Ato-visionOS/Ato-visionOS/Assets.xcassets/AppIcon.solidimagestack/Middle.solidimagestacklayer/Content.imageset/Contents.json
  Ato-visionOS/Ato-visionOS/Assets.xcassets/AppIcon.solidimagestack/Middle.solidimagestacklayer/Contents.json
  Ato-visionOS/Ato-visionOS/Assets.xcassets/Contents.json
  Ato-visionOS/Ato-visionOS/Ato_visionOSApp.swift
  Ato-visionOS/Ato-visionOS/ContentView.swift
  Ato-visionOS/Ato-visionOS/ImmersiveView.swift
  Ato-visionOS/Ato-visionOS/Info.plist
  Ato-visionOS/Ato-visionOS/ToggleImmersiveSpaceButton.swift
  Ato-visionOS/Packages/RealityKitContent/Package.realitycomposerpro/ProjectData/main.json
  Ato-visionOS/Packages/RealityKitContent/Package.realitycomposerpro/WorkspaceData/SceneMetadataList.json
  Ato-visionOS/Packages/RealityKitContent/Package.realitycomposerpro/WorkspaceData/Settings.rcprojectdata
  Ato-visionOS/Packages/RealityKitContent/Package.swift
  Ato-visionOS/Packages/RealityKitContent/README.md
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/Immersive.usda
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/Materials/GridMaterial.usda
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/Scene.usda
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.swift
Labels: Docs 📃, Setting :gear:

#5 test 할게요
  Ato-visionOS/Packages/RealityKitContent/Package.realitycomposerpro/WorkspaceData/SceneMetadataList.json
  Ato-visionOS/Packages/RealityKitContent/Package.realitycomposerpro/WorkspaceData/Settings.rcprojectdata
  Ato-visionOS/Packages/RealityKitContent/Package.realitycomposerpro/WorkspaceData/yuha.rcuserdata
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/Al.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/Ar.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/B.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/Be.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/C.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/Ca.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/Cl.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/F.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/H.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/He.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/I.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/Immersive.usda
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/K.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/Li.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/Mg.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/N.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/Na.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/Ne.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/O.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/P.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/S.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/Scene.usda
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/Si.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/textures/color_121212.hdr
Labels: Design 🎨

#7 [Setting] #2 - Xcode 폴더링
  Ato-visionOS/Ato-visionOS/App/Ato_visionOSApp.swift
  Ato-visionOS/Ato-visionOS/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  Ato-visionOS/Ato-visionOS/Resource/Assets.xcassets/AppIcon.solidimagestack/Back.solidimagestacklayer/Content.imageset/Contents.json
  Ato-visionOS/Ato-visionOS/Resource/Assets.xcassets/AppIcon.solidimagestack/Back.solidimagestacklayer/Contents.json
  Ato-visionOS/Ato-visionOS/Resource/Assets.xcassets/AppIcon.solidimagestack/Contents.json
  Ato-visionOS/Ato-visionOS/Resource/Assets.xcassets/AppIcon.solidimagestack/Front.solidimagestacklayer/Content.imageset/Contents.json
  Ato-visionOS/Ato-visionOS/Resource/Assets.xcassets/AppIcon.solidimagestack/Front.solidimagestacklayer/Contents.json
  Ato-visionOS/Ato-visionOS/Resource/Assets.xcassets/AppIcon.solidimagestack/Middle.solidimagestacklayer/Content.imageset/Contents.json
  Ato-visionOS/Ato-visionOS/Resource/Assets.xcassets/AppIcon.solidimagestack/Middle.solidimagestacklayer/Contents.json
  Ato-visionOS/Ato-visionOS/Resource/Assets.xcassets/Contents.json
  Ato-visionOS/Ato-visionOS/Resource/Extension/SIMD3+.swift
  Ato-visionOS/Ato-visionOS/Source/Common/Commands/CommandManager.swift
  Ato-visionOS/Ato-visionOS/Source/Common/Enum/ToolType.swift
  Ato-visionOS/Ato-visionOS/Source/Common/Protocol/Command.swift
  Ato-visionOS/Ato-visionOS/Source/Common/UIComponents/ToggleImmersiveSpaceButton.swift
  Ato-visionOS/Ato-visionOS/Source/Entities/AtomEntity.swift
  Ato-visionOS/Ato-visionOS/Source/Model/AppModel.swift
  Ato-visionOS/Ato-visionOS/Source/View/ContentView.swift
  Ato-visionOS/Ato-visionOS/Source/View/ImmersiveView.swift
  Ato-visionOS/Ato-visionOS/Source/ViewModel/ContentViewModel.swift
Labels: Setting :gear:

#13 [Setting] #12 - Info.plist 파일 이동
  Ato-visionOS/Ato-visionOS.xcodeproj/project.pbxproj
  Ato-visionOS/Ato-visionOS/Resource/Info.plist
Labels: Setting :gear:

#16 [UI] #15 - 주기율표 뷰 구현
  Ato-visionOS/Ato-visionOS/App/Ato_visionOSApp.swift
  Ato-visionOS/Ato-visionOS/Source/Common/UIComponents/CustomButton.swift
  Ato-visionOS/Ato-visionOS/Source/Model/Element.swift
  Ato-visionOS/Ato-visionOS/Source/Model/ElementData.swift
  Ato-visionOS/Ato-visionOS/Source/View/ElementDetailView.swift
  Ato-visionOS/Ato-visionOS/Source/View/PeriodicTableView.swift
  Ato-visionOS/Ato-visionOS/Source/View/SplitPeriodicView.swift
Labels: UI 💄

#23 [Design] #22 - 원자 상세 모형 3D 구현 (원자핵, 전자, 궤도)했습니다.
  Ato-visionOS/Ato-visionOS.xcodeproj/project.pbxproj
  Ato-visionOS/Packages/RealityKitContent/Package.realitycomposerpro/PluginData/A1CDC858-511E-427F-ABF2-2F2B941A2D18/ShaderGraphEditorPluginID/ShaderGraphEditorPluginID
  Ato-visionOS/Packages/RealityKitContent/Package.realitycomposerpro/PluginData/D0A755EC-649C-45B5-91FC-337DF28B5481/ShaderGraphEditorPluginID/ShaderGraphEditorPluginID
  Ato-visionOS/Packages/RealityKitContent/Package.realitycomposerpro/ProjectData/main.json
  Ato-visionOS/Packages/RealityKitContent/Package.realitycomposerpro/WorkspaceData/SceneMetadataList.json
  Ato-visionOS/Packages/RealityKitContent/Package.realitycomposerpro/WorkspaceData/yuha.rcuserdata
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/electron.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/ring1.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/ring2.usdz
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/ring3.usdz
Labels: Design 🎨

#29 [Design] #26 - Atom 2D UI 컴포넌트
  Ato-visionOS/Ato-visionOS/Source/Common/Enum/AtomType.swift
  Ato-visionOS/Ato-visionOS/Source/Common/UIComponents/Atom2D/Atom2D.swift
  Ato-visionOS/Ato-visionOS/Source/Common/UIComponents/Atom2D/AtomNucleus.swift
  Ato-visionOS/Ato-visionOS/Source/Common/UIComponents/Atom2D/AtomOrbit.swift
Labels: Design 🎨

#44 feat: 데이터 모델, Mock데이터, 클래스 생성
  Ato-visionOS/Ato-visionOS/Resource/Tests/MockData/DetailMoleculeMockData.swift
  Ato-visionOS/Ato-visionOS/Resource/Tests/MockData/LabMockData.swift
  Ato-visionOS/Ato-visionOS/Source/Entities/LabAtom.swift
  Ato-visionOS/Ato-visionOS/Source/Model/DetailMoleculeModel.swift
  Ato-visionOS/Ato-visionOS/Source/Model/LabModel.swift
  Ato-visionOS/Ato-visionOS/Source/View/ElementDetailView.swift
  Ato-visionOS/Ato-visionOS/Source/View/PeriodicTableView.swift
  Ato-visionOS/Ato-visionOS/Source/View/SplitPeriodicView.swift
Labels: Add 📥

#50 [Design] #46 - 이머시브 환경 수정, 물체 배치
  Ato-visionOS/Packages/RealityKitContent/Package.realitycomposerpro/PluginData/7CC341AC-C4C0-4942-98BD-A5635262AE88/ShaderGraphEditorPluginID/ShaderGraphEditorPluginID
  Ato-visionOS/Packages/RealityKitContent/Package.realitycomposerpro/PluginData/A1CDC858-511E-427F-ABF2-2F2B941A2D18/ShaderGraphEditorPluginID/ShaderGraphEditorPluginID
  Ato-visionOS/Packages/RealityKitContent/Package.realitycomposerpro/PluginData/D1244F03-F15C-4A08-A6E3-6920574CAABF/ShaderGraphEditorPluginID/ShaderGraphEditorPluginID
  Ato-visionOS/Packages/RealityKitContent/Package.realitycomposerpro/ProjectData/main.json
  Ato-visionOS/Packages/RealityKitContent/Package.realitycomposerpro/WorkspaceData/SceneMetadataList.json
  Ato-visionOS/Packages/RealityKitContent/Package.realitycomposerpro/WorkspaceData/leon.rcuserdata
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/ImmersiveSpace.usda
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/ParticleEmitterPresetTextures/dustsheet.exr
Labels: Design 🎨

#54 [Refactor] #53 - 실험실 볼륨으로 이동
  Ato-visionOS/Ato-visionOS/App/Ato_visionOSApp.swift
  Ato-visionOS/Ato-visionOS/Source/Common/Commands/SpawnAtomCommand.swift
  Ato-visionOS/Ato-visionOS/Source/Model/AppModel.swift
  Ato-visionOS/Ato-visionOS/Source/View/LabView.swift
Labels: Refactor 🔨

#28 [Feat] #27 - 실험실 분자 조합, 분해 구현했습니다.
  Ato-visionOS/Ato-visionOS/Source/Common/Commands/BondCommand.swift
  Ato-visionOS/Ato-visionOS/Source/Common/Commands/DissociateCommand.swift
  Ato-visionOS/Ato-visionOS/Source/Common/Enum/BondGeometry.swift
  Ato-visionOS/Ato-visionOS/Source/Entities/MoleculeEntity.swift
  Ato-visionOS/Ato-visionOS/Source/View/ImmersiveView.swift
  Ato-visionOS/Ato-visionOS/Source/View/ToolbarView.swift
Labels: Feat ✨

#58 [Feat] #56 - 원자 번호별로 크기 다르게 생성
  Ato-visionOS/Ato-visionOS/Source/Common/Commands/SpawnAtomCommand.swift
  Ato-visionOS/Ato-visionOS/Source/Common/Enum/AtomType.swift
  Ato-visionOS/Ato-visionOS/Source/Entities/AtomEntity.swift
  Ato-visionOS/Ato-visionOS/Source/Entities/LabAtom.swift
  Ato-visionOS/Ato-visionOS/Source/View/ImmersiveView.swift
  Ato-visionOS/Ato-visionOS/Source/View/LabView.swift
Labels: Feat ✨

#68 [Feat] #25 - 실험실 원자상세보기, 분자 결합 해제하기 기능 구현
  Ato-visionOS/Ato-visionOS/App/Ato_visionOSApp.swift
  Ato-visionOS/Ato-visionOS/Source/Common/AtomManager.swift
  Ato-visionOS/Ato-visionOS/Source/Common/Commands/BondCommand.swift
  Ato-visionOS/Ato-visionOS/Source/Common/Commands/ChangeToolCommand.swift
  Ato-visionOS/Ato-visionOS/Source/Common/Commands/DeleteCommand.swift
  Ato-visionOS/Ato-visionOS/Source/Common/Commands/DissociateCommand.swift
  Ato-visionOS/Ato-visionOS/Source/Common/Commands/MagnifyAtomCommand.swift
  Ato-visionOS/Ato-visionOS/Source/Common/MoleculeManager.swift
  Ato-visionOS/Ato-visionOS/Source/Entities/LabAtom.swift
  Ato-visionOS/Ato-visionOS/Source/Entities/LabMolecule.swift
  Ato-visionOS/Ato-visionOS/Source/Model/AppModel.swift
  Ato-visionOS/Ato-visionOS/Source/View/2D/ToolbarView.swift
  Ato-visionOS/Ato-visionOS/Source/View/Lab/LabView.swift
  Ato-visionOS/Ato-visionOS/Source/ViewModel/LabViewModel.swift
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/AllRing.usdc
Labels: Feat ✨

#71 [Feat] #70 - 분자 생성 시 일치하는 분자 검색 기능 구현
  Ato-visionOS/Ato-visionOS/Resource/Extension/String+.swift
  Ato-visionOS/Ato-visionOS/Source/Common/AtomManager.swift
  Ato-visionOS/Ato-visionOS/Source/Common/Commands/BondCommand.swift
  Ato-visionOS/Ato-visionOS/Source/Common/Enum/AtomType.swift
  Ato-visionOS/Ato-visionOS/Source/Common/MoleculeManager.swift
  Ato-visionOS/Ato-visionOS/Source/Entities/LabAtom.swift
  Ato-visionOS/Ato-visionOS/Source/Entities/LabMolecule.swift
  Ato-visionOS/Ato-visionOS/Source/Model/AtomListModel.swift
  Ato-visionOS/Ato-visionOS/Source/Model/ElementCount.swift
  Ato-visionOS/Ato-visionOS/Source/View/2D/DetailView/ElementDetailView.swift
Labels: Feat ✨

#75 [Feat] # 69 - 리뷰 반영
  Ato-visionOS/Ato-visionOS/Source/Common/UIComponents/ToggleImmersiveSpaceButton.swift
  Ato-visionOS/Ato-visionOS/Source/Model/ElementData.swift
  Ato-visionOS/Ato-visionOS/Source/View/2D/ContentView.swift
  Ato-visionOS/Ato-visionOS/Source/View/2D/DetailView/AtomDetailView.swift
  Ato-visionOS/Ato-visionOS/Source/View/2D/DetailView/ElementDetailView.swift
  Ato-visionOS/Ato-visionOS/Source/View/2D/DetailView/MoleculeDetailView.swift
  Ato-visionOS/Ato-visionOS/Source/View/2D/PeriodicTableView.swift
  Ato-visionOS/Ato-visionOS/Source/View/2D/SplitPeriodicView.swift
  Ato-visionOS/Ato-visionOS/Source/View/2D/ToolbarView.swift
  Ato-visionOS/Ato-visionOS/Source/View/Immersive/ImmersiveView.swift
  Ato-visionOS/Packages/RealityKitContent/Package.realitycomposerpro/WorkspaceData/SceneMetadataList.json
Labels: Feat ✨

#78 [Feat] #77 - 물체호버
  Ato-visionOS/Packages/RealityKitContent/Package.realitycomposerpro/WorkspaceData/SceneMetadataList.json
  Ato-visionOS/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/FinalImmersive.usda
Labels: Feat ✨

#91 [Fix] #89-윈도우레이아웃재구성
  Ato-visionOS/Ato-visionOS/App/Ato_visionOSApp.swift
  Ato-visionOS/Ato-visionOS/Source/View/2D/ContentView.swift
  Ato-visionOS/Ato-visionOS/Source/View/2D/DetailView/ElementDetailView.swift
  Ato-visionOS/Ato-visionOS/Source/View/2D/PeriodicTableView.swift
  Ato-visionOS/Ato-visionOS/Source/View/2D/SplitPeriodicView.swift
  Ato-visionOS/Ato-visionOS/Source/View/2D/ToolbarView.swift
Labels: Fix :bug:

#95 [Fix] #79 - 설명창symbol잘림수정
  Ato-visionOS/Ato-visionOS/Source/View/2D/DetailView/MoleculeDetailView.swift
Labels: Fix :bug:

#97 [Feat] #80 - 이멀시브 스페이스에서 탄소 클릭시 실험실 탄소 원자 생성
  Ato-visionOS/Ato-visionOS/Source/View/Immersive/ImmersiveView.swift
Labels: Feat ✨
